version: "3.7"

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: galaxy
    ports:
      - 5432:5432
  janus1:
    image: bb-janus:latest
    restart: always
    volumes:
      - ./misc/janus/config/dev:/usr/janusgxy/etc/janus
    ports:
      - 8088:8088
      - 7088:7088
  app:
    build: .
    environment:
      DB_URL: postgres://user:password@db/galaxy?sslmode=disable
    ports:
      - 8080:8080
    depends_on:
      - db
      - janus1
    command: ["/wait-for", "db:5432", "--", "./gxydb-api"]
